# Generated by Django 5.0.1 on 2024-11-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_discussion'),
        ('projects', '0002_remove_collaborator_project_remove_collaborator_user_and_more'),
    ]

    operations = [
    ]
