# Generated by Django 5.0.6 on 2024-11-27 16:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
