# Generated by Django 5.0.6 on 2024-11-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="data",
            field=models.JSONField(),
        ),
    ]
